### PR TITLE
196 make local spatial subset issues

### PR DESCRIPTION
**Pull request by kbernat**

### CODE REVIEW

**Comment by JanisGailis** [comment]
Code looks good. However, I can't test it fully now, there seems to be a problem with downloading. It's likely a portal problem, as Marco was experiencing it as well!

**Comment by JanisGailis** [comment]
Running this:
```python
from cate.core.ds import DATA_STORE_REGISTRY
import cate.ops as ops
from cate.util import ConsoleMonitor
import xarray as xr

monitor = ConsoleMonitor()

data_store = DATA_STORE_REGISTRY.get_data_store('esa_cci_odp')
local_store = DATA_STORE_REGISTRY.get_data_store('local')
soil_remote_sources = data_store.query('soil')

zemgale = '23.5, 56.3, 25.0, 57.0'
local_store.remove_data_source('local.soil.mon')
soil_remote_sources[0].make_local(local_name='soil.mon',
                                  time_range='2007-01-01, 2007-01-05',
                                  region=zemgale,
                                  monitor=monitor)
```

Gives me this stack trace:
```shell
Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: started
Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc
Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   2% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: lon
Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   4% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: lat
Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   5% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: time
Traceback (most recent call last):
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/netCDF4_.py", line 60, in __getitem__
    data = getitem(self.get_array(), key)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/common.py", line 66, in robust_getitem
    return array[key]
  File "netCDF4/_netCDF4.pyx", line 3753, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:40536)
  File "netCDF4/_netCDF4.pyx", line 4470, in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:51236)
IndexError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_make_local_subset.py", line 17, in <module>
    monitor=monitor)
  File "/home/ccitbx/Development/cate-core/cate/ds/esa_cci_odp.py", line 798, in make_local
    self._make_local(local_ds, time_range, region, var_names, monitor)
  File "/home/ccitbx/Development/cate-core/cate/ds/esa_cci_odp.py", line 722, in _make_local
    local_netcdf.store_dataset(var_dataset)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/common.py", line 209, in store_dataset
    self.store(dataset, dataset.attrs)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/common.py", line 246, in store
    *args, **kwargs)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/common.py", line 215, in store
    unlimited_dims=unlimited_dims)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/netCDF4_.py", line 288, in set_variables
    super(NetCDF4DataStore, self).set_variables(*args, **kwargs)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/common.py", line 227, in set_variables
    name, v, check, unlimited_dims=unlimited_dims)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/netCDF4_.py", line 332, in prepare_variable
    return nc4_var, variable.data
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/core/dataarray.py", line 392, in data
    return self.variable.data
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/core/variable.py", line 267, in data
    return self.values
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/core/variable.py", line 308, in values
    return _as_array_or_item(self._data)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/core/variable.py", line 184, in _as_array_or_item
    data = np.asarray(data)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/core/indexing.py", line 375, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/ccitbx/miniconda3/envs/cate/lib/python3.5/site-packages/xarray/backends/netCDF4_.py", line 71, in __getitem__
    raise IndexError(msg)
IndexError: The indexing operation you are attempting to perform is not valid on netCDF4.Variable object. Try loading your data into memory first by calling .load().
```

**Comment by kbernat** [comment]
@JanisGailis thanks for the report. It's fixed now - you can try again.

**Comment by JanisGailis** [comment]
This works as expected now.

One note though, in global attributes of the dataset, this can be found:
```shell
    geospatial_lat_min:         -56.25
    geospatial_lat_max:         -23.25
    geospatial_lon_min:         23.5
    geospatial_lon_max:         228.5
```

Is that something you add at some point, or does it come from opendap?

**Comment by JanisGailis** [comment]
Closes #196

**Comment by JanisGailis** [comment]
I say - go ahead and merge this :)

**Pull request merged**
