### PR TITLE
159 anomaly

### PR DESCRIPTION
**Pull request by JanisGailis**
Anomaly calculation operations have been overhauled and are now properly tested.

### CODE REVIEW

**Comment by JanisGailis** [comment]
Closes #159

**Comment by JanisGailis** [comment]
Looks like AppVeyor tests are failing because I'm trying to write to disk as part of some tests. Note that some tests absolutely require this (e.g., testing dask integration).

**Comment by mzuehlke** [comment]
@JanisGailis maybe writing the tests like in xarray may help: https://github.com/pydata/xarray/blob/master/xarray/tests/test_backends.py#L497

**Comment by JanisGailis** [comment]
Yes, this is exactly what came to my mind as well :) Will see if it works!

**Comment by JanisGailis** [comment]
Implemented their solution - fancy error ignoring when on Windows :)

**Comment by JanisGailis** [comment]
If anyone gets round to merging these, it's probably a good idea to start reviewing/merging the older PRs first, to avoid possible conflicts.

**Comment by forman** [comment]
Hi Janis, I merged the other 2. Please resolve this one to go ahead!

**Comment by JanisGailis** [comment]
Resolved!

**Comment by JanisGailis** [comment]
I'll take the liberty to merge this based on your previous comment.

**Pull request merged**
