### PR TITLE
160 diff op

### PR DESCRIPTION
**Pull request by JanisGailis**
A more robust difference operation has been implemented and tested.

Tests have been written for the ds_arithmetics operation and found bugs fixed.

### CODE REVIEW

**Comment by JanisGailis** [comment]
Closes #160

**Comment by JanisGailis** [comment]
If anyone is looking at this, wait a bit before merging, I want to add one more test for both ops.

**Comment by JanisGailis** [comment]
Done

**Comment by forman** [comment]
I like the diff op, but I still disagree with the arithmetic op. We should really move to an op, where users can specify a normal expression which we either 

1. `eval` without globals but with a safe locals env.
2. and/or use `numexpr` also for a performance boost.

**Pull request merged**
