### PR TITLE
172 generic types ops

### LINKED ISSUE #158: Use generic types in user interfaces and docs
The new generic types introduced by #130 must be used in the various user interfaces

- [ ] API used in IPython Notebooks (fix code)
- [x] CLI, e.g. display `cate op list <op>` and argument parsing, `cate res set <op> <arg1>=<val1> ...`
- [x] GUI, e.g. display of op help in OPERATIONS panel, parameter entry editors, ...

I have no clue how we tell **Sphinx** to use simple type names instead of using totally confusing expressions composed of `typings.Union`.

### LINKED ISSUE #163: Harmonization should convert MJD times to datetime
Currently we handle MJD (Modified Julian Date) in the temporal subset routine explicitly. More and more operations rely on having datetime as the dtype for the time coordinate of a dataset. Hence, MJD time should be handled during harmonization instead.

### LINKED ISSUE #172: Use generic types in all ops
All ops should be reviewed to make sure they use the new generic types.

See also #158

### PR DESCRIPTION
**Pull request by JanisGailis**
All operations now use new types, tests updated accordingly

harmonization routine handles Julian day time.

The UC09 notebook now uses make_local. I'm mostly interested in you all checking out the notebook to see how we have to use the new ds approach.

closes #172  closes #163  closes #158

### CODE REVIEW

**Comment by JanisGailis** [comment]
Closes #172 #163 #158

**Comment by JanisGailis** [comment]
How can I see what flake8 complains about?

**Comment by forman** [comment]
Exactly! Marco, how do we know what's wrong?

**Comment by mzuehlke** [comment]
* use the [Details link](https://travis-ci.org/CCI-Tools/cate-core/jobs/223209603) which leads to the travis logs.
* scroll down to the end
* exapand the line `flake8 --exit-zero|tee flake8_report.txt`

`./test/ops/test_harmonize.py:70:26: E226 missing whitespace around arithmetic operator`
`./test/ops/test_plot.py:39:29: E251 unexpected spaces around keyword / parameter equals`
`./test/ops/test_plot.py:39:31: E251 unexpected spaces around keyword / parameter equals`


Or run flake8 locally or look at pycharm warnings.

**Comment by JanisGailis** [comment]
Cool, thanks!

**Comment by JanisGailis** [comment]
Can this be merged? It mainly contains only some changes to operations so that they use the new types, as well as updates to the corresponding tests.

**Comment by mzuehlke** [comment]
This looks good. The `make_local` section could be written simpler.

Instead of:

    oz_remote_sources[0].make_local(local_name='ozone.mon',
                                time_range='2007-01-01, 2008-05-01',
                                monitor=monitor)
    oz_local_ds = local_store.query('local.ozone.mon')[0]
    oz = oz_local_ds.open_dataset()

You could write:

    oz_local_ds = oz_remote_sources[0].make_local(local_name='ozone.mon',
                                time_range='2007-01-01, 2008-05-01',
                                monitor=monitor)
    oz = oz_local_ds.open_dataset()

**Comment by JanisGailis** [comment]
@mzuehlke The reason I did it that way was because make_local raises an error if a name already exists. This way the notebook can be run multiple times until the ```ds``` interface is changed somehow.

**Comment by JanisGailis** [comment]
Thanks!

**Comment by mzuehlke** [comment]
@JanisGailis valid reason.

**Pull request merged**
