### PR TITLE
223 jg subset spatial fix

### LINKED ISSUE #223: subset_spatial() op must adjust global attributes
`subset_spatial()` operation must adjust global attributes such as `geospatial_lat_min`.

### LINKED ISSUE #294: A uniform method of adjusting global attributes of altered datasets
### Expected behavior

Some operations, such as ```subset_spatial```, ```subset_temporal```, ```coregistration```, have a potential of changing dataset properties that should be properly reflected in the global attributes of affected datasets. There should be a uniform method of addressing this.

### Actual behavior

Logic that handles updates to global attributes is part of particular operations.

### Implementation hints

Create utility functions in ```ops/normalize.py``` or ```ops/utility.py``` that hamdle this. Such as ```adjust_spatial_attrs```, ```adjust_temporal_attrs``` that work with attributes denoted in [Attribute Convention for Data Discovery](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery). Specifically:

```shell
Spatial:
geospatial_lat_min:         -90.0
geospatial_lat_max:         90.0
geospatial_lon_min:         -180.0
geospatial_lon_max:         180.0
geospatial_vertical_min:    0.0
geospatial_vertical_max:    0.0
spatial_resolution:         1km at Equator
geospatial_lat_units:       degrees_north
geospatial_lon_units:       degrees_east
geospatial_lat_resolution:  0.5
geospatial_lon_resolution:  0.5

Temporal:
time_coverage_start:        20010101T000000Z
time_coverage_end:          20010101T235959Z
time_coverage_duration:     P1D
time_coverage_resolution:   P1D
```

As global attributes are optional, it is better to have no attribute than to have a wrong attribute.

### Task list
- [x] Create ```adjust_spatial_attrs```
- [x] Create ```adjust_temporal_attrs```
- [x] Use in ```subset_spatial```
- [x] Use in ```subset_temporal```
- [x] Use in ```coregistration```
- [x] Check if has to be used in other operations
- [x] Update operation development guide
- [x] Update CHANGE.md

### Specifications 
Cate 0.9.0dev3

### PR DESCRIPTION
**Pull request by JanisGailis**
A uniform way for handling updates to global attributes along with associated changes in operations, tests and documentation.

Closes #294 
Closes #223

### CODE REVIEW

**Comment by JanisGailis** [comment]
For some reason the auto-tag stuff has leaked into this. I'll try to weed it out somehow.

**Comment by JanisGailis** [comment]
```git revert --no-commit``` does wonders.

**Comment by forman** [comment]
Hi Janis, the computation of spatial boundaries is not exact. We must take *grid cell boundaries* into account. Each value in the `lon`, `lat` coordinate variables usually refer to *cell centers*, especially if the coordinate variables  `lon_bnds`, `lat_bnds` are given. Their elements are pairs that provide each cell's lower and upper bound. If they are given, then the outer limits are given by

    lat_min = min(lat_bnds[0][0], lat_bnds[-1][1])
    lat_max = max(lat_bnds[0][0], lat_bnds[-1][1])

If not, the boundaries are

    lat_res = abs(lat[1] - lat[0])
    lat_min = min(lat[-1], lat[0]) - 0.5 * lat_res
    lat_max = max(lat[-1], lat[0]) + 0.5 * lat_res

equidistant grids presumed.

There is already code that computes boundaries as described: [workspace.py](https://github.com/CCI-Tools/cate-core/blob/c424afc48d2df078c598aacc3fd4308fde6ea6ea/cate/core/workspace.py#L325-L381)

**Comment by JanisGailis** [comment]
Do you have a conventions reference for this?

I've seen CCI datasets that treat lat_min pointed to a pixel boundary, but I've also seen plenty pointing to the actual 'minimum' of the coordinate vector.

**Comment by forman** [comment]
It is in the CF convention. As most CCI datasets apply them you'll find lat[0] = 90 - 0.5 * res and lat[-1] = -90 + 0.5 * res, so that the boundaries are -90, +90 for global coverage.

**Comment by forman** [comment]
> but I've also seen plenty pointing to the actual 'minimum' of the coordinate vector.

Do you remember which ones?

**Comment by JanisGailis** [comment]
I'll check.

By the way, why do you take min/max here:
```
lat_min = min(lat[-1], lat[0]) - 0.5 * lat_res
lat_max = max(lat[-1], lat[0]) + 0.5 * lat_res
```

Does that imply working also with 'degrees_south' and 'degrees_west'?

**Comment by forman** [comment]
It is also common to store lats upside down, SST does that, that is `lat` increases with the grid's `y` index.

**Comment by forman** [comment]
https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/metadata/DataDiscoveryAttConvention.html

See explanation of `geospatial_ ...`

**Comment by forman** [comment]
Here is a nice example:

<xarray.Dataset>
Dimensions:                     (time: 7, x: 720, y: 360)
Coordinates:
    lat                         (y, x) float32 89.75 89.75 89.75 89.75 89.75 ...
    lon                         (y, x) float32 -179.75 -179.25 -178.75 ...
  * time                        (time) int64 2001001 2001002 2001003 2001004 ...
Dimensions without coordinates: x, y
Data variables:
    BHR_VIS                     (time, y, x) float64 nan nan nan nan nan nan ...
    BHR_NIR                     (time, y, x) float64 nan nan nan nan nan nan ...
    ...
    Relative_Entropy            (time, y, x) float64 nan nan nan nan nan nan ...
    Weighted_Number_of_Samples  (time, y, x) float64 nan nan nan nan nan nan ...
    Goodness_of_Fit             (time, y, x) float64 nan nan nan nan nan nan ...
    Data_Mask                   (time, y, x) float64 nan nan nan nan nan nan ...
    Solar_Zenith_Angle          (time, y, x) float64 nan nan nan nan nan nan ...
Attributes:
    title:                      QA4ECV Albedo Product
    institution:                Mullard Space Science Laboratory, Department ...
    source:                     Satellite observations, BRDF/Albedo Inversion...
    history:                    QA4ECV Processing, 2014-2017
    references:                 www.qa4ecv.eu
    tracking_id:                49b8d6eb-1503-4400-91a4-1f1a8f87f12b
    Conventions:                CF-1.6
    product_version:            1.0
    summary:                    This dataset contains Level-3 daily surface b...
    keywords:                   Albedo, TIP, FAPAR
    id:                         Qa4ecv.albedo.avh_geo.2001001_upscaled.nc
    naming_authority:           ucl.ac.uk
    keywords_vocabulary:        
    cdm_data_type:              Alb
    comment:                    These data were produced in the frame of the ...
    date_created:               20170613T081550Z
    creator_name:               Mullard Space Science Laboratory, Department ...
    creator_url:                www.ucl.ac.uk/mssl
    creator_email:              qa4ecv-land-all@ucl.ac.uk
    project:                    QA4ECV - European Union Framework Program 7
    geospatial_lat_min:         -90.0
    geospatial_lat_max:         90.0
    geospatial_lon_min:         -180.0
    geospatial_lon_max:         180.0
    geospatial_vertical_min:    0.0
    geospatial_vertical_max:    0.0
    time_coverage_start:        20010101T000000Z
    time_coverage_end:          20010101T235959Z
    time_coverage_duration:     P1D
    time_coverage_resolution:   P1D
    standard_name_vocabulary:   NetCDF Climate and Forecast (CF) Metadata Con...
    license:                    QA4ECV Data Policy: free and open access
    platform:                   NOAA-xx, Meteosat MFG, Meteosat MSG, GOES, GMS
    sensor:                     AVHRR, MVIRI, SEVIRI, Imager, VISSR
    spatial_resolution:         1km at Equator
    geospatial_lat_units:       degrees_north
    geospatial_lon_units:       degrees_east
    geospatial_lat_resolution:  0.5
    geospatial_lon_resolution:  0.5

**Comment by JanisGailis** [comment]
You mean lat[0] would be something like -180 and lat[-1] would be 180? I think that's the case in all datasets we manage to open. In fact, we had a problem with data access when that's not the case, so I think all of them are now reversed to that, if not already the case.

**Comment by forman** [comment]
No!

**Comment by forman** [comment]
Lat cannot be 180  :)

**Comment by JanisGailis** [comment]
Yes, -90, 90 :)

**Comment by forman** [comment]
We have both cases in CCI

**Comment by JanisGailis** [comment]
Well, yes, we don't handle lat[0]=90 grids well. We even had an issue on this. I think we're reversing them now upon access.

**Comment by forman** [comment]
Btw, my example above is a bad one as it uses 2D lat, lon coordinate arrays.

**Comment by mzuehlke** [comment]
oc-cci has it's lat values going from +90 to -90

**Comment by forman** [comment]
Which I like

**Comment by JanisGailis** [comment]
From
From ```esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1```

```
    geospatial_lon_resolution:   0.50
    geospatial_lat_resolution:   0.50
    geospatial_lat_min:          -89.75
    geospatial_lat_max:          89.75
    geospatial_lon_min:          -179.75
    geospatial_lon_max:          179.75
    geospatial_lat_units:        degrees_north
    geospatial_lon_units:        degrees_east
    geospatial_vertical_min:     0.0
    geospatial_vertical_max:     0.0
```

**Comment by forman** [comment]
That's definitely wrong!

**Comment by forman** [comment]
Or it is correct, because they cut off half a grid cell at both ends for some reason (e.g. anti-meridian problem, he, he).

**Comment by JanisGailis** [comment]
OK, yes, I agree, if that denotes a bounding box of the dataset, then it shouldn't cut pixels. As simple as that :)

**Comment by JanisGailis** [comment]
See: https://github.com/CCI-Tools/cate-core/issues/196

**Comment by forman** [comment]
Yepp.

**Comment by JanisGailis** [comment]
Yes, we don't reverse it upon reading, sm data goes from 90 to -90:
```
 * lat      (lat) float32 16.875 16.625 16.375 16.125 15.875 15.625 15.375
```

OK, this is good to realize (again, I guess), as that might make a difference in some ops.

Cool, then I'm off to implementing the changes you suggested! Thanks for taking the time to look at the PR! :)

**Comment by JanisGailis** [comment]
@forman @mzuehlke Good to go now?

**Comment by forman** [comment]
Great

**Pull request merged**
