### PR TITLE
292 jg autotags

### LINKED ISSUE #292: Automatically add module name to 'tags' list of an operation
### Expected behavior

Operations should have a tag that is the same as it's module name. E.g. 'correlation' for all operations in the correlation.py module.
See also #280 

### Actual behavior

When ```@op()``` is invoked, module name gets added to the tags list automatically. Only additional tags should be added by hand as required.

### Specifications 
Cate 0.9.0dev3

### PR DESCRIPTION
**Pull request by JanisGailis**
Introduce automatic operation tagging with the module name.

Closes #292

### CODE REVIEW

**Comment by forman** [comment]
Good! However, I don't like the expression `if default_tags[0] not in properties['tags']` in the `op` decorator. First, what are `default_tags`? Second, we assume there is only one and it is the module's name, so we actually mean `if module_name not in properties['tags']`. 

I must confess, I'm currently struggling whether auto-tagging is really a good approach at all. I tend to say no. Marco too.

But implementation is great!  :-)

**Comment by JanisGailis** [comment]
```default_tags``` would be tags created during function introspection. This is of course only the module name. However, it must be a list of strings to be iterable by string, not by character later on wherever it is used. Hence the notation. It could be of course spelled out. ```module_name = default_tags[0]```.

Haha, yes, I'm not sure about that myself, see my last comment  on the other issue (https://github.com/CCI-Tools/cate-core/issues/280). But then we have to make a decision on the set of tags that we use and/or the strategy of using/not using module name as part of tags.

**Comment by forman** [comment]
Are you ok if we drop aut-tagging?
If so, I owe you some beers, because I brought up the idea.

**Comment by JanisGailis** [comment]
Sure, it took like 20 minutes anyway! But then please comment in #280 in the strategy on using/not using module names in tag list!

**Pull request closed without merging**
