### PR TITLE
168 opennig local data souces

### LINKED ISSUE #168: open local data sources
CLI should use the data source ID prefix ("local.") to identify the data store it searches for the data source ID first, then search all other data stores. This means, local data stores currently cannot be used from the CLI.

Current workaround:
open any esa odp data source first and then the local one

### PR DESCRIPTION
**Pull request by kbernat**
closes #168, #202

### CODE REVIEW

**Comment by mzuehlke** [comment]
Hi @kbernat, why implement in both relevant subclasses local and odp the same logic. It may be better to implement this in the abstract class and have no diverging implementations in the subclasses at all.

**Comment by forman** [comment]
I agree, but prefer composition over inheritance.

**Comment by mzuehlke** [comment]
class DataSource(metaclass=ABCMeta):
        def matches_filter(self, name=None) -> bool:
            """Test if this data source matches the given *constraints*."""
            if name and name != self.name:
                return False
            return True

    class LocalDataSource(DataSource):
        def matches_filter(self, name: str = None) -> bool:
            return name.lower() in self.name.lower()

    class EsaCciOdpDataSource(DataSource):
        def matches_filter(self, name: str = None) -> bool:
            return name.lower() in self.name.lower()

But where to delegate to ?
**And** the implementations in the subclasses can not handle `None` which is the default.

**Comment by forman** [comment]
Oops, haven't seen the code. Yes, just move it up and deal with Non/empty name constraint.

**Comment by kbernat** [comment]
I thought that exact name comparison is still "default behavior", but both ODP and local should act more loosely.  Now I see that there no such requirement.
@mzuehlke why DataSource.matches_filter() why we need None, and why then it returns True?

**Comment by forman** [comment]
The idea was that `name` is a constraint. If it is not given, we have no constraint, thus we want an unconstrained result which is all data sources.

**Comment by kbernat** [comment]
If there is no name provided then we don't run filter anyway.
```
    def query(self, name: str = None, monitor: Monitor = Monitor.NONE) -> Sequence['DataSource']:
        self._init_data_sources()
        if name:
            result = [data_source for data_source in self._data_sources if data_source.matches_filter(name)]
        else:
            result = self._data_sources
        return result
```
Anyway, I will move implementation to DataSource but will left None handling as is now in DataSource class (True when name is None).

**Pull request merged**
