### PR TITLE
280 tags

### LINKED ISSUE #280: Limit possible operation tags
### Expected behavior

Operations should only use tags from a limited and agreed-on set.

- [x] aggregate
- [x] anomaly
- [x] arithmetics
- [x] coregistration
- [x] correlation
- [x] index
- [x] io
- [x] outliers
- [x] pandas
- [x] plot
- [x] resampling
- [x] select
- [x] subset
- [x] timeseries
- [x] utility

### Actual behavior

We have 20+ op tags. See dropdown list in GUI.

### Specifications 

0.9.0.dev3

### PR DESCRIPTION
**Pull request by JanisGailis**
Closes #280 

* Make sure all used tags are from set: maybe module name && given list
* Update developers' guide with the tags list
* Move pandas_fillna to the utility module
* Fix tests
* Update CHANGES.md

### CODE REVIEW

**Comment by JanisGailis** [comment]
@mzuehlke Merge when ready :)

**Comment by JanisGailis** [comment]
Ahh, I removed from the __init__ completely where it was just moved.

But then, it should be in the documentation, no? Or being 'internal' means it's also not in docs?

**Comment by mzuehlke** [comment]
I wasn't sure if you removed it from the init by intention. then it should be removed from the doc, too.
But if stays in the init it should stay in the doc.

**Comment by JanisGailis** [comment]
Pushed

**Comment by mzuehlke** [comment]
I will merge this later

**Comment by JanisGailis** [comment]
You closed it without merging. I'll take the liberty and merge it.

**Comment by mzuehlke** [comment]
sorry, I thought I had pressed the merge button 😢

**Comment by JanisGailis** [comment]
It happens to all of us, especially late in the evening :)

**Pull request merged**
