### PR TITLE
145 uc02 api demo

### LINKED ISSUE #146: UC02 CLI Happy Path
Create a CLI Demo for UC02

### LINKED ISSUE #327: Happy Path UC02
### Comment

Relates to: #146 
I conducted a preliminary happy path for Use Case 2 (see appended sh-script). When invoking it I run into some problems (see 'Steps to reproduce'-section).

### Steps to reproduce the problem

1. Invoke Cate-CLI
2.
cate ds copy esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1 --name CLOUD_2006_2009_region_7_48_10_52 --time '2006-01-01,2009-12-31' --region '7,48,10,52'
3.
cate ws new
4.
cate res open cloud local.CLOUD_2006_2009_region_7_48_10_52
5.
cate res set cloud_lta long_term_average ds=@cloud var="cfc"
6.
cate res set station read_csv file="/data/sherzog/cate-0.9.0.dev4/UC02/produkt_klima_Tageswerte_20050715_20151231_07341_output2.txt" delimiter=";" index_col="time"

(Link to testdata: https://github.com/CCI-Tools/cate-e2e/blob/master/testdata/produkt_klima_Tageswerte_20050715_20151231_07341_vers002.txt)
7.
cate res set station_ds from_dataframe df=@station
8.
cate res set station_outl detect_outliers ds=@station_ds var=" precipitation" threshold_low=0.00 threshold_high=100.00 quantiles=False
9.
cate res set station_lta long_term_average ds=@station_outl var="precipitation"
10.
cate res set res_8 plot ds=@station_ds var="precipitation" file="/data/sherzog/cate-0.9.0.dev4/UC02/station_ds_precipitation.jpg"

### Comment Problems:
Step 9. returns the following message:
''cate res: error: Long term average operation expects a dataset with the time coordinate of type datetime64[ns], but received object. Running the harmonization operation on this dataset may help''

Step 10. returns the following:
''Executing 3 workflow step(s): done                                                                                                                                                                                                           
cate res: error: Plotting requires coordinates to be numeric or dates.''

### Idea:

I think the errors are due to the fact, that cate does not recognize the time-variable from the testdata well. Or the format in the testdata is wrong.

### Appendix:
[uc02.txt](https://github.com/CCI-Tools/cate-core/files/1227265/uc02.txt)

### Specifications 

cate-0.9.0.dev4, on linux

### PR DESCRIPTION
**Pull request by JanisGailis**
Closes #327 
Closes #146 

Add a UC2 happy path, fix UC6 happy path. Append some relevant operations to enable faux-polymorphism, fix tests.

### CODE REVIEW

**Comment by JanisGailis** [comment]
If I remember correctly, we came up with that name for parameters that can be a dataset or a dataframe together with Norman. But I'm not sure if it wasn't just for sake of demonstration on how the fake polymorphism would work! This has to be checked with him which one to use ds or dsf.

**Comment by mzuehlke** [comment]
OK, didn't remember that, will check wit @forman

**Comment by mzuehlke** [comment]
Will you do the dsf -> ds renaming?
If you are busy with the S&T event I could do that and then merge it.

**Comment by JanisGailis** [comment]
I just wanted to do it! Should be done in 10 with running the tests! I'll let you know if I can't make it!
Thanks!

**Comment by JanisGailis** [comment]
(y)

**Pull request merged**
